import { Fresca, Unna } from "next/font/google";
import "./globals.css";

const fresca = Fresca({
  weight: "400",
  variable: "--font-fresca",
  subsets: ["latin"],
});

const unna = Unna({
  weight: ["400", "700"],
  variable: "--font-unna",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${fresca.variable} ${unna.variable}`}>
        {children}
      </body>
    </html>
  );
}
